// Code generated by protoc-gen-go. DO NOT EDIT.
// source: downlink_frame.proto

package storage

import (
	fmt "fmt"
	gw "github.com/kamicuu/chirpstack-api/go/v3/gw"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DownlinkFrame struct {
	// Token.
	Token uint32 `protobuf:"varint,1,opt,name=token,proto3" json:"token,omitempty"`
	// DevEUI.
	DevEui []byte `protobuf:"bytes,2,opt,name=dev_eui,json=devEui,proto3" json:"dev_eui,omitempty"`
	// Device queue item ID.
	DeviceQueueItemId int64 `protobuf:"varint,3,opt,name=device_queue_item_id,json=deviceQueueItemId,proto3" json:"device_queue_item_id,omitempty"`
	// Multicast Group ID.
	MulticastGroupId []byte `protobuf:"bytes,4,opt,name=multicast_group_id,json=multicastGroupId,proto3" json:"multicast_group_id,omitempty"`
	// Multicast queue item ID.
	MulticastQueueItemId int64 `protobuf:"varint,5,opt,name=multicast_queue_item_id,json=multicastQueueItemId,proto3" json:"multicast_queue_item_id,omitempty"`
	// Downlink frames.
	DownlinkFrame *gw.DownlinkFrame `protobuf:"bytes,6,opt,name=downlink_frame,json=downlinkFrame,proto3" json:"downlink_frame,omitempty"`
	// Routing Profile ID.
	RoutingProfileId []byte `protobuf:"bytes,7,opt,name=routing_profile_id,json=routingProfileId,proto3" json:"routing_profile_id,omitempty"`
	// Encrypted FOpts (LoRaWAN 1.1).
	EncryptedFopts bool `protobuf:"varint,8,opt,name=encrypted_fopts,json=encryptedFopts,proto3" json:"encrypted_fopts,omitempty"`
	// Network session encryption key (for FOpts).
	NwkSEncKey           []byte   `protobuf:"bytes,9,opt,name=nwk_s_enc_key,json=nwkSEncKey,proto3" json:"nwk_s_enc_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DownlinkFrame) Reset()         { *m = DownlinkFrame{} }
func (m *DownlinkFrame) String() string { return proto.CompactTextString(m) }
func (*DownlinkFrame) ProtoMessage()    {}
func (*DownlinkFrame) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d3c072e28619f9c, []int{0}
}

func (m *DownlinkFrame) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DownlinkFrame.Unmarshal(m, b)
}
func (m *DownlinkFrame) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DownlinkFrame.Marshal(b, m, deterministic)
}
func (m *DownlinkFrame) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DownlinkFrame.Merge(m, src)
}
func (m *DownlinkFrame) XXX_Size() int {
	return xxx_messageInfo_DownlinkFrame.Size(m)
}
func (m *DownlinkFrame) XXX_DiscardUnknown() {
	xxx_messageInfo_DownlinkFrame.DiscardUnknown(m)
}

var xxx_messageInfo_DownlinkFrame proto.InternalMessageInfo

func (m *DownlinkFrame) GetToken() uint32 {
	if m != nil {
		return m.Token
	}
	return 0
}

func (m *DownlinkFrame) GetDevEui() []byte {
	if m != nil {
		return m.DevEui
	}
	return nil
}

func (m *DownlinkFrame) GetDeviceQueueItemId() int64 {
	if m != nil {
		return m.DeviceQueueItemId
	}
	return 0
}

func (m *DownlinkFrame) GetMulticastGroupId() []byte {
	if m != nil {
		return m.MulticastGroupId
	}
	return nil
}

func (m *DownlinkFrame) GetMulticastQueueItemId() int64 {
	if m != nil {
		return m.MulticastQueueItemId
	}
	return 0
}

func (m *DownlinkFrame) GetDownlinkFrame() *gw.DownlinkFrame {
	if m != nil {
		return m.DownlinkFrame
	}
	return nil
}

func (m *DownlinkFrame) GetRoutingProfileId() []byte {
	if m != nil {
		return m.RoutingProfileId
	}
	return nil
}

func (m *DownlinkFrame) GetEncryptedFopts() bool {
	if m != nil {
		return m.EncryptedFopts
	}
	return false
}

func (m *DownlinkFrame) GetNwkSEncKey() []byte {
	if m != nil {
		return m.NwkSEncKey
	}
	return nil
}

func init() {
	proto.RegisterType((*DownlinkFrame)(nil), "storage.DownlinkFrame")
}

func init() {
	proto.RegisterFile("downlink_frame.proto", fileDescriptor_6d3c072e28619f9c)
}

var fileDescriptor_6d3c072e28619f9c = []byte{
	// 309 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x91, 0xdf, 0x4a, 0xc3, 0x30,
	0x14, 0xc6, 0xa9, 0x73, 0x7f, 0x3c, 0xb3, 0xd3, 0x85, 0xc2, 0x8a, 0x57, 0xd5, 0x1b, 0x7b, 0x31,
	0x36, 0x50, 0x04, 0x1f, 0xc0, 0x4d, 0x8a, 0x37, 0x5a, 0x1f, 0x20, 0xcc, 0xe6, 0xac, 0x84, 0xae,
	0x49, 0x4d, 0x93, 0x85, 0xbd, 0x81, 0x8f, 0x2d, 0x69, 0xc7, 0xb4, 0x97, 0xf9, 0x7e, 0x1f, 0xe7,
	0x97, 0x93, 0x40, 0xc0, 0xa4, 0x15, 0x3b, 0x2e, 0x0a, 0xba, 0x55, 0x9b, 0x12, 0x17, 0x95, 0x92,
	0x5a, 0x92, 0x61, 0xad, 0xa5, 0xda, 0xe4, 0x78, 0x33, 0xce, 0xed, 0x32, 0xb7, 0x6d, 0x7a, 0xf7,
	0xd3, 0x03, 0xff, 0xe5, 0x58, 0x5f, 0xbb, 0x36, 0x09, 0xa0, 0xaf, 0x65, 0x81, 0x22, 0xf4, 0x22,
	0x2f, 0xf6, 0xd3, 0xf6, 0x40, 0x66, 0x30, 0x64, 0xb8, 0xa7, 0x68, 0x78, 0x78, 0x16, 0x79, 0xf1,
	0x65, 0x3a, 0x60, 0xb8, 0x5f, 0x19, 0x4e, 0x96, 0x10, 0x30, 0xdc, 0xf3, 0x0c, 0xe9, 0xb7, 0x41,
	0x83, 0x94, 0x6b, 0x2c, 0x29, 0x67, 0x61, 0x2f, 0xf2, 0xe2, 0x5e, 0x3a, 0x6d, 0xd9, 0x87, 0x43,
	0x89, 0xc6, 0x32, 0x61, 0x64, 0x0e, 0xa4, 0x34, 0x3b, 0xcd, 0xb3, 0x4d, 0xad, 0x69, 0xae, 0xa4,
	0xa9, 0x5c, 0xfd, 0xbc, 0x19, 0x7a, 0x7d, 0x22, 0xaf, 0x0e, 0x24, 0x8c, 0x3c, 0xc1, 0xec, 0xaf,
	0xdd, 0x35, 0xf4, 0x1b, 0x43, 0x70, 0xc2, 0xff, 0x25, 0xcf, 0x30, 0xe9, 0x3e, 0x42, 0x38, 0x88,
	0xbc, 0x78, 0xfc, 0x30, 0x5d, 0xe4, 0x76, 0xd1, 0xd9, 0x37, 0xf5, 0x59, 0x67, 0xfd, 0x39, 0x10,
	0x25, 0x8d, 0xe6, 0x22, 0xa7, 0x95, 0x92, 0x5b, 0xbe, 0x43, 0xe7, 0x1a, 0xb6, 0xd7, 0x3b, 0x92,
	0xf7, 0x16, 0x24, 0x8c, 0xdc, 0xc3, 0x15, 0x8a, 0x4c, 0x1d, 0x2a, 0x8d, 0x8c, 0x6e, 0x65, 0xa5,
	0xeb, 0x70, 0x14, 0x79, 0xf1, 0x28, 0x9d, 0x9c, 0xe2, 0xb5, 0x4b, 0xc9, 0x2d, 0xf8, 0xc2, 0x16,
	0xb4, 0xa6, 0x28, 0x32, 0x5a, 0xe0, 0x21, 0xbc, 0x68, 0x26, 0x82, 0xb0, 0xc5, 0xe7, 0x4a, 0x64,
	0x6f, 0x78, 0xf8, 0x1a, 0x34, 0x3f, 0xf2, 0xf8, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x89, 0x93, 0x41,
	0x6f, 0xbf, 0x01, 0x00, 0x00,
}
